# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  # - smartcontractkit/chainlink@1.4.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0-solc-0.7
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0-solc-0.7"
      # - "chainlinkoperator=smartcontractkit/chainlink@1.4.1"
# automatically fetch contract sources from Etherscan
autofetch_sources: True

dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: rinkeby
  development:
    keyhash: "0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4"
    fee: 100000000000000000
    jobId: "29fa9aa13bf1468788b7cc4a500a45b8"
    update_interval: 60
    verify: False
  ganache:
    keyhash: "0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4"
    fee: 100000000000000000
    jobId: "29fa9aa13bf1468788b7cc4a500a45b8"
    update_interval: 60
    verify: False
  rinkeby:
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    fee: 100000000000000000
    oracle: "0xf08A5588de3433eA07d397ccb48f8455AcBD2351"
    # oracle: "0xe30E3CE8D147A6Dd8C498687151a7e71a33ba3A8"
    node: "0x468c0847Ef2aF0722E51a1CEa4F8d986a106cE14"
    init_audit_jobId: "3da800ea5aad4800a2792a6ceb49f535"
    conclude_audit_jobId: "1801a1abdaaf4f4fb6a0ce45789ae7ba"
    get_byte_jobId: "d9f48c2ca789409798599d232b9ef55c"


    verify: True


wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
