type = "directrequest"
schemaVersion = 1
name = "register_audit_03"
externalJobID = "c403f0e0-90fb-40ba-b22c-9c16651eabdb"
maxTaskDuration = "0s"
contractAddress = "0x2afD14158F5937fE49751d8Ff2F615eBeCfA0084"
minIncomingConfirmations = 0
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    fetch        [type=bridge name="register_audit"  requestData="{\\"id\\": $(jobSpec.externalJobID), \\"data\\": { \\"name\\": $(decode_cbor.name), \\"admin_jid\\":$(decode_cbor.admin_jid), \\"bond\\":$(decode_cbor.bond)}}"]
    parse        [type=jsonparse path="data,response" data="$(fetch)"]
    encode_data  [type=ethabiencode abi="(uint256 response)" data="{ \\"response\\": $(parse) }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type=ethtx to="0x2afD14158F5937fE49751d8Ff2F615eBeCfA0084" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> encode_data -> encode_tx -> submit_tx
"""
